apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: seaweed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ghcr.io/your-org/seaweed-auth:latest
          env:
            - name: AUTH_PORT
              value: "4000"
            - name: MONGO_URI
              value: mongodb://mongo.seaweed.svc.cluster.local:27017/buttblastr_auth
            - name: CORS_ORIGIN
              value: http://localhost:3000
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: seaweed
spec:
  selector:
    app: auth
  ports:
    - port: 4000
      targetPort: 4000

