apiVersion: apps/v1
kind: Deployment
metadata:
  name: content
  namespace: seaweed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
        - name: content
          image: ghcr.io/your-org/seaweed-content:latest
          env:
            - name: CONTENT_PORT
              value: "4003"
            - name: MONGO_URI
              value: mongodb://mongo.seaweed.svc.cluster.local:27017/buttblastr_content
            - name: CORS_ORIGIN
              value: http://localhost:3000
          ports:
            - containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: content
  namespace: seaweed
spec:
  selector:
    app: content
  ports:
    - port: 4003
      targetPort: 4003

