apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: seaweed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/your-org/seaweed-frontend:latest
          env:
            - name: NEXT_PUBLIC_LOW_LATENCY
              value: "true"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: seaweed
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort

